---
# tasks file for Master
- name: Configuring Yum repo for kubernetes
  blockinfile:
           path: /etc/yum.repos.d/kubernetes.repo
           create: True
           marker: "#<!-- {mark} ANSIBLE MANAGED BLOCK -->"
           block: |
                 [kubernetes]
                 name=Kubernetes
                 baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
                 enabled=1
                 gpgcheck=1
                 repo_gpgcheck=1
                 gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
                 exclude=kubelet kubeadm kubectl
  register: file

- name: updating yum
  command: yum repolist -y
  when: file.changed == True

- name: Installing required packages
  yum:
        name: "{{ packages }}"
        state: present
        disable_excludes: kubernetes
  loop: "{{ packages }}"

- name: Enable kubelet service
  service:
         name: kubelet
         state: started
         enabled: yes
  ignore_errors: yes

- name: Enable docker service
  service:
         name: docker
         state: started
         enabled: yes
  ignore_errors: yes

- name: Changing CGROUP Driver of Docker To systemd
  copy:
         dest: /etc/docker/daemon.json
         content: |
                 {
                         "exec-opts": ["native.cgroupdriver=systemd"]
                         }
  register: docker

- name: restart docker
  service:
     name: docker
     state: restarted
  when: docker.changed == True

- name:
  sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: '1'
        sysctl_set: yes

- name: Pulling Images
  command: kubeadm config images pull
  
- name: kubeadm 
  shell: kubeadm init --pod-network-cidr={{ network }}/16  --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem
  ignore_errors: yes

#- name: kubelet
#  shell: kubelet --cloud-provider=aws
# ignore_errors: yes
#
#- name: kube-apiserver
# shell: kube-apiserver --cloud-provider=aws
# ignore_errors: yes
#
#- name: kube-controller-manager
# shell: kube-controller-manager --cloud-provider=aws
# ignore_errors: yes

- name: creating directory
  shell: mkdir -p $HOME/.kube
  ignore_errors: yes
  
- name: coping admin.conf file to .kube directory
  copy:
     src: /etc/kubernetes/admin.conf
     dest: $HOME/.kube/config
     owner: ec2-user
     group: ec2-user
     remote_src: yes
    
- name: edit flannel conf
  template:
     src: roles/Master/files/flannel.yml
     dest: flannel.yml
    
- name: apply flannel conf
  command: kubectl apply -f flannel.yml 
   
- name: retriving join link 
  command: kubeadm token create --print-join-command 
  register: joinlink

- name: Storing joininglink in local host
  local_action: copy content={{ joinlink.stdout }} dest=roles/Worker/files/joinlink.sh
    
- debug:
    var: joinlink.stdout

